### ISSUE TITLE
Switch to MIT License

### ISSUE THREAD

**Issue by mindninjaX** [DevsTrons/Hello-World#10]
I noticed that currently the project is Unlicensed. This could lead to unwanted buying & selling of community's work.

I recommend switching to the MIT License in order to add the restrictions to prevent such issues. 

The project will maintain it's usability & distribution.

**Comment by amino19** [comment]
@mindninjaX : Okay boss!

**Comment by mindninjaX** [comment]
Let me handle this. Assigning it to myself.

**Comment by amino19** [comment]
@mindninjaX : Work must be done through PR! :slightly_smiling_face: 
Pl avoid such practices...

**Comment by mindninjaX** [comment]
@amino19 Sorry sir 🤕😭
