### ISSUE TITLE
[Feature] Update README.md

### ISSUE THREAD

**Issue by amino19** [devstrons/hello-world#38]
**Is your feature request related to a problem? Please describe.**

Currently, README.md consists project's tagline, enhance in a way, it's necessary for our project. The content here will be include in the documentation description as well.

**Describe the solution you'd like**

It should be done in such a way, so beginner will try to understand the project properly.

**Describe alternatives you've considered**

No alternate plan.

**Additional context**

Contributor can take reference from other organization project as well! :slightly_smiling_face:

**Comment by rishabhrathore055** [comment]
pls assign me this @amino19

**Comment by Panquesito7** [comment]
I am working on this. 🙂
