### ISSUE TITLE
Extra indentation in the hello wolrd program given in the readme

### ISSUE THREAD

**Issue by tusqasi** [devstrons/hello-world#60]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/24749908/132940838-d04e4603-878d-4ab6-a61f-4bbb94d8c30b.png">

When someone copies that snippet to start with a new language,  they will be greeted with an extra indentation.

**Comment by vsnthdev** [comment]
I'm planning on implementing a universal copy button that will automatically strip all white spaces and fix the indentation no matter how it is on the markdown file... A PR for that will be submitted soon.

**Comment by amino19** [comment]
@tusqasi: fixed in #62
