### ISSUE TITLE
[FEATURE] <Add links to the Navigation Menu>

### ISSUE THREAD

**Issue by Rajkumar-stackcoder** [devstrons/hello-world#70]
### Is your feature request related to a problem? Please describe.

![Screenshot 2021-09-24 122334](https://user-images.githubusercontent.com/83064473/134631276-5fdfcd66-3b03-4b35-b580-edc2f11b0da8.png)

Links are not working in Navigation Menu

### Describe the solution you'd like

Add links to Nevigation Menu for discord and about me section

**Comment by adil14788** [comment]
@Rajkumar-stackcoder is anyone working on it can i help ???

**Comment by Panquesito7** [comment]
> @Rajkumar-stackcoder is anyone working on it can i help ???

I don't think anyone is working on it. Feel free to work on it. 🙂
